config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books, :rents
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: books
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  author      :string           not null
#  category    :string           default("")
#  description :text             default("")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  deleted_at  :datetime
#

class Book < ApplicationRecord
  validates :name, :author, presence: true
  validates :name, :author, :category, length: { in: 1..255 }
  validates :description, length: { in: 25..6000 }

  scope :without_destroyed, -> { where(deleted_at: nil) }
  has_many :rents

  # We hide books which had been rented becouse
  # we want to have history rent
  def delete
    can_be_destoryed? ? destroy : hide_book
  end

  def hide_book
    update(deleted_at: Time.current)
  end

  def can_be_destoryed?
    rents.blank?
  end

  def rented?
    rents.present? && any_book_rented?
  end

  def any_book_rented?
    rents.each do |rent|
      return true unless rent.return?
    end
    false
  end
end

app/models/rent.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: rents
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  book_id     :integer          not null
#  return_date :date             not null
#  return?     :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, :book_id, :return_date, presence: true
  validate :book_can_be_rent_only_by_one_person_at_this_same_time, on: :create

  def book_can_be_rent_only_by_one_person_at_this_same_time
    if Rent.where(book_id: book, return?: false).exists?
      errors.add(:book_id, "can't be twice rent in the same time")
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  name                   :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :rents
  has_many :books, through: :rents

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by(email: data['email'])

    # Uncomment the section below if you want users to be created
    # if they don't exist
    user ||= User.create(name: data['name'],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/book_controller.rb
class BookController < ApplicationController

  def index
    @books =  Book.all
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  def index
    @books = Book.includes(:rents).page params[:page]
  end

  def show; end

  def edit; end

  def update
    if @book.update(book_params)
      flash.now[:notice] = 'book modificated'
      redirect_to @book
    else
      flash.now[:error] = 'Failed to modificated book in database'
      render :edit
    end
  end

  def destroy
    @book.delete
    respond_to do |format|
      format.js { render layout: false }
      format.html { redirect_to books_path }
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
      flash.now[:notice] = 'book has been created'
    else
      flash.now[:error] = 'Failed to save book'
      render :new
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :author, :category, :description)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: %i[show edit update destroy return_book]
  def index
    @rents = current_user.rents.includes(:book).page params[:page]
  end

  def edit
    update
  end

  def update
    if @rent.update(return?: true)
      flash[:notice] = 'book returned'
    else
      flash[:error] = 'Failed to return book'
    end
    redirect_to rents_path
  end

  def new
    @rent = current_user.rents.new
  end

  def create
    @rent = current_user.rents.new(rent_params)
    set_return_date
    if @rent.save
      flash[:notice] = 'book has been rented'
      redirect_to @rent.book
    else
      flash[:error] = 'Failed to rent the book'
      redirect_to books_path
    end
  end

  private

  def set_return_date
    @rent.return_date = Time.current + 30.days
  end

  def set_rent
    @rent = current_user.rents.find(params[:id])
  end

  def rent_params
    params.require(:rent).permit(:book_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_form.html.slim
.book_form
  =simple_form_for @book do |b|
    =b.input :name
    =b.input :author
    =b.input :category
    =b.input :description
    =b.button :submit

app/views/books/destroy.js.erb
$('.delete_book').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/books/edit.html.slim
=render partial: 'form', locals: {book: @book}

app/views/books/index.html.slim
=paginate @books
table.table.table-hover.book-index
  tr
    th #
    th name
    th author
    th category
    th delete
    th edit
    th rent
  -@books.each_with_index do |book, index|
    tr
      td =index
      td =link_to book.name, book
      td =book.author
      td =book.category
      td =link_to 'Delete', book,
                           method: :delete,
                           data: {confirm: 'Are you siure?'},
                           remote: true,
                           class: 'delete_book'
      td =link_to 'Edit', edit_book_path(book),
                          class: 'edit_book'
      td
        -if book.rented?
          | rented
        -else
          =link_to 'Rent', rents_path(rent: {book_id: book.id}),
                                        method: :create,
                                        class: 'rent_book'
=paginate @books

app/views/books/new.html.slim
=render 'form'

app/views/books/show.html.slim
.book
  table.table.table-hover
    tr
      td name
      td =@book.name
    tr
      td author
      td =@book.author
    tr
      td category
      td =@book.category
    tr
      td delete
      td =link_to 'Delete', @book,
                             method: :delete,
                             data: {confirm: 'Are you siure?'},
                             class: 'delete_book'
    tr
      td edit
      td =link_to 'Edit', edit_book_path,
                          class: 'edit_book'
    tr
      td rent
      td
        -if @book.rented?
          | rented
        -else
          =link_to 'Rent', rents_path(rent: {book_id: @book.id}),
                                        method: :create,
                                        class: 'rent_book'

  h2 Description
  .book_description
    =@book.description

app/views/layouts/_login_links.html.slim
- if notice
  p.notice
    - notice
- if alert
  p.alert
    - alert
- if user_signed_in?
  |
  = current_user.email
  = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
  = link_to "Logout", destroy_user_session_path, method: :delete, :class =>'navbar-link'

app/views/layouts/_nav.html.slim
ul.nav.nav-tabs
  li.nav-item
    a.nav-link.active
      =link_to 'Books', books_path
  li.nav-item
    a.nav-link
      =link_to 'My rents', rents_path
  li.nav-item
    a.nav-link
      =link_to 'Add book', new_book_path
  li.nav-item
    a.nav-link.loggin_links
      =render '/layouts/login_links'

app/views/layouts/_notice.html.slim
- if flash[:notice]
  .alert.alert-success role="alert"
    = flash[:notice]
- if flash[:error]
  .alert.alert-danger role="alert"
    = flash[:error]

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Library
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .jumbotron
      h1 Library

    =render '/layouts/notice'
    =render '/layouts/nav'
    =yield

app/views/rents/index.html.slim
=paginate @rents
table.table.table-hover.book-index
  tr
    th #
    th name
    th start
    th return_date
    th return
  -@rents.each_with_index do |rent, index|
    tr
      td =index
      td =link_to rent.book.name, rent.book
      td =rent.created_at
      td =rent.return_date
      td
        -if rent.return?
          |returned
        -else
          =link_to 'return', edit_rent_path(rent),
                              class: 'edit_book'
=paginate @rents

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}",
      omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>